CREATE TABLE permitidos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nick VARCHAR(32) UNIQUE NOT NULL,
	senha CHAR(32) NOT NULL
);

CREATE TABLE noticias (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author INT NOT NULL,
	FOREIGN KEY(author) REFERENCES permitidos(id)
);

CREATE TABLE novidades (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author INT NOT NULL,
	FOREIGN KEY(author) REFERENCES permitidos(id)
);

CREATE TABLE lojaitems (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	descricao TEXT NOT NULL
);

CREATE TABLE buttonsitems (
	id INT PRIMARY KEY AUTO_INCREMENT,
	texto VARCHAR(25) NOT NULL,
	link VARCHAR(255) NOT NULL,
	cor VARCHAR(10) NOT NULL,
	itemId INT NOT NULL,
	FOREIGN KEY(itemId) REFERENCES lojaitems(id)
);

CREATE TABLE modalitems (
	id INT PRIMARY KEY AUTO_INCREMENT,
	itemId INT NOT NULL,
	titulo VARCHAR(50) NOT NULL,
	conteudo TEXT NOT NULL,
	FOREIGN KEY(itemId) REFERENCES lojaitems(id)
);